//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbs2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discuss_infos
    {
        public int id { get; set; }
        public string theme { get; set; }
        public string AllContent { get; set; }
        public string time { get; set; }
        public string author { get; set; }
        public string solve { get; set; }
    }
}
