//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbs2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply_infos
    {
        public int id { get; set; }
        public int theme_id { get; set; }
        public string reply { get; set; }
        public string ReplyAuthor { get; set; }
        public string ReplyTime { get; set; }
    }
}
