//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbs2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yicraft_infos
    {
        public int ID { get; set; }
        public string loginname { get; set; }
        public string mail { get; set; }
        public string actualname { get; set; }
        public Nullable<int> idcard { get; set; }
        public Nullable<int> age { get; set; }
    }
}
